# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
import time
ser=serial.Serial("com4",9600);


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 80, 311, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 310, 120, 40))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 150, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(160, 150, 231, 22))
        self.horizontalSlider.setMinimumSize(QtCore.QSize(231, 0))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(160, 210, 231, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(255)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 91, 21))
        
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 101, 21))
     
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 20, 121, 31))
       
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 260, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Square Wave"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Sine Wave"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Triangle Wave"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Staircase Wave"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Ramp Wave"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Sawtooth"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.label_2.setText(_translate("MainWindow", "Amplitude"))
        self.label_3.setText(_translate("MainWindow", "Frequency"))
        self.label_4.setText(_translate("MainWindow", "Wave Generator"))
        self.pushButton.clicked.connect(self.button)

    def button(self):
        ampint = self.horizontalSlider.value()
        freqint = self.horizontalSlider_2.value()
        ampstr = str(ampint)
        freqstr = str(freqint)
        for i in range(0, 3, 1):
            if (len(ampstr) == 3):
                break;
            ampstr = '0' + ampstr
        for i in range(0, 3, 1):
            if (len(freqstr) == 3):
                break;
            freqstr = '0' + freqstr

        if (self.comboBox.currentIndex() == 0):
            x = "@0" + ampstr + freqstr + ";"
            print(x)
            ser.reset_output_buffer()
            ser.write(bytes(x, "utf-8"))
        if (self.comboBox.currentIndex() == 1):
            x = "@3" + ampstr + freqstr + ";"
            ser.reset_output_buffer()
            ser.write(bytes(x, "utf-8"))
        if (self.comboBox.currentIndex() == 2):
            x = "@2" + ampstr + freqstr + ";"
            ser.reset_output_buffer()
            ser.write(bytes(x, "utf-8"))
        if (self.comboBox.currentIndex() == 3):
            x = "@1" + ampstr + freqstr + ";"
            ser.reset_output_buffer()
            ser.write(bytes(x, "utf-8"))
        if (self.comboBox.currentIndex() == 4):
            x = "@4" + ampstr + freqstr + ";"
            ser.reset_output_buffer()
            ser.write(bytes(x, "utf-8"))
        if (self.comboBox.currentIndex() == 5):
            x = "@5" + ampstr + freqstr + ";"
            ser.reset_output_buffer()
            ser.write(bytes(x, "utf-8"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
